: '
./exe  --mode pack --layout binstatdfs --intertwine 6 --blocksize 16 --modelfilename ~/pacset/models/cifarnew.json --packfilename ~/pacset/models/packedbinstat.txt --metadatafilename ~/pacset/models/metabinstat.txt --datafilename ~/pacset/data/cifar-10.csv --numthreads 1 --package sklearn --algorithm randomforest --task classification

./exe  --mode pack --layout bindfs --intertwine 6 --blocksize 16 --modelfilename ~/pacset/models/cifarnew.json --packfilename ~/pacset/models/packedbindfs.txt --datafilename ~/pacset/data/cifar-10.csv --metadatafilename ~/pacset/models/metabindfs.txt --numthreads 1 --package sklearn --algorithm randomforest --task classification
./exe  --mode pack --layout binbfs --intertwine 6 --blocksize 16 --modelfilename ~/pacset/models/cifarnew.json --packfilename ~/pacset/models/packedbinbfs.txt --datafilename ~/pacset/data/cifar-10.csv --metadatafilename ~/pacset/models/metabinbfs.txt --numthreads 1 --package sklearn --algorithm randomforest --task classification
./exe  --mode pack --layout bindfsstat --intertwine 6 --blocksize 16 --modelfilename ~/pacset/models/cifarnew.json --packfilename ~/pacset/models/packedbindfsstat16.txt --datafilename ~/pacset/data/cifar-10.csv --metadatafilename ~/pacset/models/metabindfsstat16.txt --numthreads 8 --package sklearn --algorithm randomforest --task classification
./exe  --mode both --layout binstatblock --intertwine 3 --blocksize 128 --modelfilename ~/pacset/models/cifarnew.json --packfilename ~/pacset/models/packedbinblockstat16.txt --datafilename ~/pacset/data/cifar-10.csv --metadatafilename ~/pacset/models/metabinblockstat16.txt --numthreads 1 --package sklearn --algorithm randomforest --task classification > out6
./exe  --mode both --layout binstatblock --intertwine 4 --blocksize 128 --modelfilename ~/pacset/models/cifarnew.json --packfilename ~/pacset/models/packedbinblockstat16.txt --datafilename ~/pacset/data/cifar-10.csv --metadatafilename ~/pacset/models/metabinblockstat16.txt --numthreads 1 --package sklearn --algorithm randomforest --task classification > out6
./exe  --mode both --layout binstatblock --intertwine 2 --blocksize 128 --modelfilename ~/pacset/models/cifarnew.json --packfilename ~/pacset/models/packedbinblockstat16.txt --datafilename ~/pacset/data/cifar-10.csv --metadatafilename ~/pacset/models/metabinblockstat16.txt --numthreads 1 --package sklearn --algorithm randomforest --task classification > out6
./exe  --mode both --layout binstatblock --intertwine 1 --blocksize 128 --modelfilename ~/pacset/models/cifarnew.json --packfilename ~/pacset/models/packedbinblockstat16.txt --datafilename ~/pacset/data/cifar-10.csv --metadatafilename ~/pacset/models/metabinblockstat16.txt --numthreads 1 --package sklearn --algorithm randomforest --task classification > out6
./exe  --mode both --layout binstatblock --intertwine 5 --blocksize 128 --modelfilename ~/pacset/models/cifarnew.json --packfilename ~/pacset/models/packedbinblockstat16.txt --datafilename ~/pacset/data/cifar-10.csv --metadatafilename ~/pacset/models/metabinblockstat16.txt --numthreads 1 --package sklearn --algorithm randomforest --task classification > out6
./exe  --mode both --layout statblock --intertwine 0 --blocksize 128 --modelfilename ~/pacset/models/cifarnew.json --packfilename ~/pacset/models/packedbinblockstat16.txt --datafilename ~/pacset/data/cifar-10.csv --metadatafilename ~/pacset/models/metabinblockstat16.txt --numthreads 1 --package sklearn --algorithm randomforest --task classification > out6
./exe  --mode pack --layout binstatblock --intertwine 4 --blocksize 16 --modelfilename ~/pacset/models/cifarnew.json --packfilename ~/pacset/models/packedbinstatblock16_8.txt --datafilename ~/pacset/data/cifar-10.csv --metadatafilename ~/pacset/models/metabinstatblock16_8.txt --numthreads 8 --package sklearn --algorithm randomforest --task classification
./exe  --mode pack --layout binstatblock --intertwine 4 --blocksize 8 --modelfilename ~/pacset/models/cifarnew.json --packfilename ~/pacset/models/packedbinstatblock16_16.txt --datafilename ~/pacset/data/cifar-10.csv --metadatafilename ~/pacset/models/metabinstatblock16_16.txt --numthreads 16 --package sklearn --algorithm randomforest --task classification
./exe  --mode pack --layout binstatblock --intertwine 4 --blocksize 4 --modelfilename ~/pacset/models/cifarnew.json --packfilename ~/pacset/models/packedbinstatblock16_32.txt --datafilename ~/pacset/data/cifar-10.csv --metadatafilename ~/pacset/models/metabinstatblock16_32.txt --numthreads 32 --package sklearn --algorithm randomforest --task classification
./exe  --mode both --layout binstatblock --intertwine 4 --blocksize 32 --modelfilename ~/pacset/models/cifarnew.json --packfilename ~/pacset/models/packedbinbstatlock16_4.txt --datafilename ~/pacset/data/cifar-10.csv --metadatafilename ~/pacset/models/metabinstatblock16_4.txt --numthreads 4 --package sklearn --algorithm randomforest --task classification
./exe  --mode both --layout binstatblock --intertwine 4 --blocksize 16 --modelfilename ~/pacset/models/cifarnew.json --packfilename ~/pacset/models/packedbinbstatlock16_2.txt --datafilename ~/pacset/data/cifar-10.csv --metadatafilename ~/pacset/models/metabinstatblock16_2.txt --numthreads 2 --package sklearn --algorithm randomforest --task classification
./exe  --mode both --layout binstatdfs --intertwine 4 --blocksize 16 --modelfilename ~/pacset/models/cifarnew.json --packfilename ~/pacset/models/packedbinstatdfs16.txt --datafilename ~/pacset/data/cifar-10.csv --metadatafilename ~/pacset/models/metabinstatdfs16.txt --numthreads 8 --package sklearn --algorithm randomforest --task classification
./exe  --mode both --layout bindfs --intertwine 4 --blocksize 16 --modelfilename ~/pacset/models/cifarnew.json --packfilename ~/pacset/models/packedbindfs16.txt --datafilename ~/pacset/data/cifar-10.csv --metadatafilename ~/pacset/models/metabindfs16.txt --numthreads 8 --package sklearn --algorithm randomforest --task classification
./exe  --mode both --layout binbfs --intertwine 4 --blocksize 16 --modelfilename ~/pacset/models/cifarnew.json --packfilename ~/pacset/models/packedbinbfs16.txt --datafilename ~/pacset/data/cifar-10.csv --metadatafilename ~/pacset/models/metabinbfs16.txt --numthreads 8 --package sklearn --algorithm randomforest --task classification
./exe  --mode both --layout bfs --intertwine 0 --blocksize 16 --modelfilename ~/pacset/models/cifarnew.json --packfilename ~/pacset/models/packedbfs16.txt --datafilename ~/pacset/data/cifar-10.csv --metadatafilename ~/pacset/models/metabfs16.txt --numthreads 8 --package sklearn --algorithm randomforest --task classification
./exe  --mode both --layout dfs --intertwine 0 --blocksize 16 --modelfilename ~/pacset/models/cifarnew.json --packfilename ~/pacset/models/packeddfs16.txt --datafilename ~/pacset/data/cifar-10.csv --metadatafilename ~/pacset/models/metadfs16.txt --numthreads 8 --package sklearn --algorithm randomforest --task classification
./exe  --mode both --layout blockstat --intertwine 0 --blocksize 16 --modelfilename ~/pacset/models/cifarnew.json --packfilename ~/pacset/models/packedblockstat16.txt --datafilename ~/pacset/data/cifar-10.csv --metadatafilename ~/pacset/models/metablockstat16.txt --numthreads 8 --package sklearn --algorithm randomforest --task classification
./exe  --mode both --layout binblockstat --intertwine 4 --blocksize 128 --modelfilename ~/pacset/models/cifarnew.json --packfilename ~/pacset/models/packedblockstat1.txt --datafilename ~/pacset/data/cifar-10.csv --metadatafilename ~/pacset/models/blockstat.txt --numthreads 1 --package sklearn --algorithm randomforest --task classification

./exe  --mode both --layout binblockstat --intertwine 4 --blocksize 128 --modelfilename ~/pacset/models/cifarnew.json --packfilename ~/pacset/models/packedblockstat2.txt --datafilename ~/pacset/data/cifar-10.csv --metadatafilename ~/pacset/models/blockstat2.txt --numthreads 2 --package sklearn --algorithm randomforest --task classification

./exe  --mode both --layout binblockstat --intertwine 4 --blocksize 128 --modelfilename ~/pacset/models/cifarnew.json --packfilename ~/pacset/models/packedblockstat4.txt --datafilename ~/pacset/data/cifar-10.csv --metadatafilename ~/pacset/models/blockstat4.txt --numthreads 4 --package sklearn --algorithm randomforest --task classification

./exe  --mode both --layout binblockstat --intertwine 4 --blocksize 128 --modelfilename ~/pacset/models/cifarnew.json --packfilename ~/pacset/models/packedblockstat8.txt --datafilename ~/pacset/data/cifar-10.csv --metadatafilename ~/pacset/models/blockstat8.txt --numthreads 8 --package sklearn --algorithm randomforest --task classification

./exe  --mode both --layout binblockstat --intertwine 4 --blocksize 128 --modelfilename ~/pacset/models/cifarnew.json --packfilename ~/pacset/models/packedblockstat16.txt --datafilename ~/pacset/data/cifar-10.csv --metadatafilename ~/pacset/models/blockstat16.txt --numthreads 16 --package sklearn --algorithm randomforest --task classification
'

./exe  --mode both --layout binblockstat --intertwine 4 --blocksize 128 --modelfilename ~/pacset/models/cifarnew.json --packfilename ~/pacset/models/packedblockstat32.txt --datafilename ~/pacset/data/cifar-10.csv --metadatafilename ~/pacset/models/blockstat32.txt --numthreads 32 --package sklearn --algorithm randomforest --task classification

./exe  --mode both --layout binblockstat --intertwine 4 --blocksize 128 --modelfilename ~/pacset/models/cifarnew.json --packfilename ~/pacset/models/packedblockstat64.txt --datafilename ~/pacset/data/cifar-10.csv --metadatafilename ~/pacset/models/blockstat64.txt --numthreads 64 --package sklearn --algorithm randomforest --task classification
